# Generated by Django 2.2.3 on 2019-07-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donors',
            name='password',
        ),
    ]
