# Generated by Django 2.2.3 on 2019-07-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_remove_donors_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='age',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='donors',
            name='mob_no',
            field=models.CharField(default='', max_length=12),
        ),
    ]
