# Generated by Django 2.2.3 on 2019-07-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='donors',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
