# Generated by Django 2.2.3 on 2019-07-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hospital_name', models.CharField(max_length=30)),
                ('blood_group', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('mob_no', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
