# Generated by Django 2.2.3 on 2019-07-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='messages',
            name='mes',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='requests',
            name='hospital_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='requests',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
